# Tensors
---

## Introduction
> Torch Tensors vs Numpy Array
- torch tensor are similar to numpy ndarrays and can share the same underlying memory except torch tensors are optimized for automatic differentation

## Initializing a tensor

In [1]:
import torch
import numpy as np

In [2]:
# Direct from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data, dtype=torch.int32)
print(x_data)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [3]:
# From numpy array
np_data = np.array(data) # create np ndarray
x_np = torch.from_numpy(np_data) # create torch tensor from np ndarray
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [4]:
# From tensors
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float32) # overrides the datatype of x
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]], dtype=torch.int32) 

Random Tensor: 
 tensor([[0.4425, 0.7644],
        [0.3997, 0.9644]]) 



In [5]:
# Random or constant initialization
shape = (5,10)
x_rand = torch.rand(shape, dtype=torch.float32) # uniform random values between 0 and 1
x_ones = torch.ones(shape)
x_zeros = torch.zeros(shape)
x_randint = torch.randint(low=0, high=10, size=shape) # random integers from low to high

## Tensor Attributes
> Among the more important ones are: `shape`, `dtype`, `device`

In [7]:
print(x_data.shape)
print(x_data.dtype)
print(x_data.device) 

torch.Size([2, 2])
torch.int32
cpu


## Tensor Operations

In [18]:
# Set device agnostic code,
# we move our tensors to accelerator if available, otherwise we use CPU
device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else "cpu"
x = torch.rand(3,3).to(device)
x

tensor([[0.3281, 0.3926, 0.1702],
        [0.9070, 0.0241, 0.7848],
        [0.9465, 0.4156, 0.8198]], device='cuda:0')

In [19]:
# Splicing
print(x[1:, 1:])

tensor([[0.0241, 0.7848],
        [0.4156, 0.8198]], device='cuda:0')


In [20]:
# Joining tensors with torch.cat()

In [27]:
x2 = torch.rand(4,3).to(device)
x3 = torch.cat([x, x2], dim=0) # concatenate along rows 
print(x3, x3.shape)

x4 = torch.rand(3,4).to(device)
x5 = torch.cat([x, x4], dim=1) # concatenate along columns
print(x5, x5.shape)

tensor([[0.3281, 0.3926, 0.1702],
        [0.9070, 0.0241, 0.7848],
        [0.9465, 0.4156, 0.8198],
        [0.5509, 0.1810, 0.1086],
        [0.4746, 0.7486, 0.8263],
        [0.2994, 0.2630, 0.5490],
        [0.8110, 0.0752, 0.4954]], device='cuda:0') torch.Size([7, 3])
tensor([[0.3281, 0.3926, 0.1702, 0.9108, 0.7676, 0.8454, 0.9081],
        [0.9070, 0.0241, 0.7848, 0.4588, 0.3301, 0.7014, 0.3173],
        [0.9465, 0.4156, 0.8198, 0.3955, 0.8825, 0.8414, 0.9428]],
       device='cuda:0') torch.Size([3, 7])
